Touchgrass/Controllers/CreateActivityController.cs
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Touchgrass.Models;
using Newtonsoft.Json;

namespace Touchgrass.Controllers;

[Authorize]
public class CreateActivityController : Controller
{
    private readonly ILogger<CreateActivityController> _logger;

    private readonly IWebHostEnvironment _environment;

    public CreateActivityController(ILogger<CreateActivityController> logger, IWebHostEnvironment environment)
    {
        _logger = logger;
        _environment = environment;
    }

    [HttpPost]
    public IActionResult CreateActivity(List<IFormFile> Img)
    {
        var notFormatFormData = new Dictionary<string, string>();
        var formData = new Dictionary<string, object>();

        foreach (var (key, value) in Request.Form)
        {
            notFormatFormData[key] = value;
        }
        foreach (var (key, value) in notFormatFormData){
            Console.WriteLine($"{key},{value}");
        }
        formData["Title"] = notFormatFormData["Title"];
        formData["MaxMember"] = int.Parse(notFormatFormData["MaxMember"]);
        formData["Member"] = new List<string>();
        formData["Host"] = new Dictionary<string, string>();
        formData["Ids"] = new Random().Next(10000000);
        formData["Description"] = notFormatFormData["Description"];

        if (!notFormatFormData.ContainsKey("Tag"))
        {
            Console.WriteLine('p');
            notFormatFormData["Tag"] = "";
        }
        Console.WriteLine(notFormatFormData["Tag"]);
        string tagsString = notFormatFormData["Tag"].ToString() ?? "";
        List<string> tagsList = string.IsNullOrEmpty(tagsString) ? new List<string>() : new List<string>(tagsString.Split(','));
        formData["Tag"] = tagsList;

        formData["Place"] = notFormatFormData["Place"];

        var filePaths = new List<string>();
        if (Img != null && Img.Count > 0)
        {
            foreach (var uploadedFile in Img)
            {
                string uploadsFolder = Path.Combine(_environment.WebRootPath, "pic", "activity");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                string uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(uploadedFile.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    uploadedFile.CopyTo(fileStream);
                }

                string relativePath = Path.Combine("pic", "activity", uniqueFileName);
                filePaths.Add(relativePath);
            }
            formData["Img"] = filePaths;
        }
        else formData["Img"] = new List<string>();
        var host_name = HttpContext.Session.GetString("Name");
        var usersjson = System.IO.File.ReadAllText("./Database/User.json");
        var users = JsonConvert.DeserializeObject<List<User>>(usersjson);
        var host = users.Find(u => u.Name == host_name);
        Member Host = new Member
        {
            Users = host,
            Status = "Host"
        };
        List<Member> memList = new List<Member>();
        memList.Add(Host);
        formData["Host"] = Host;
        formData["Member"] = memList;

        DateTime RecruitEnd = DateTime.Parse(notFormatFormData["Date"]).AddDays(-1);
        formData["RecruitEnd"] = RecruitEnd.ToString("dd/MM/yyyy");

        DateTime expireDate = DateTime.Parse(notFormatFormData["Date"]).AddDays(7);
        formData["ExpireDate"] = expireDate.ToString("dd/MM/yyyy");
        
        DateTime Date = DateTime.Parse(notFormatFormData["Date"]);
        formData["Date"] = Date.ToString("dd/MM/yyyy");

        string json = System.IO.File.ReadAllText("./Database/Activity.json");
        List<Dictionary<string, object>> fileContents = JsonConvert.DeserializeObject<List<Dictionary<string, object>>>(json);
        fileContents.Add(formData);
        string jsons = JsonConvert.SerializeObject(fileContents, Formatting.Indented);
        System.IO.File.WriteAllText("./Database/Activity.json", jsons);

        return RedirectToAction("Index", "Home");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


}

Touchgrass/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Touchgrass.Models;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc.Abstractions;




namespace Touchgrass.Controllers;
[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    
    public IActionResult Index()
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var act = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        return View(act);
    }

    [HttpPost]
    public IActionResult Index(List<string> tag, string date, string keyword)
    {

        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var act = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        
        if (tag.Count != 0){
            var tagFiltered = act.FindAll(ex => ex.Tag.Any(x => tag.Any(y => y == x)));
            act = tagFiltered;
        }

        if (date != null){
            char[] dateAsChars = date.ToCharArray();
            dateAsChars[0] = date[8];
            dateAsChars[1] = date[9];
            dateAsChars[2] = '/';
            dateAsChars[3] = date[5];
            dateAsChars[4] = date[6];
            dateAsChars[5] = '/';
            dateAsChars[6] = date[0];
            dateAsChars[7] = date[1];
            dateAsChars[8] = date[2];
            dateAsChars[9] = date[3];
            string newdate = new string(dateAsChars);
            var dateFiltered = act.FindAll(ex => ex.Date == newdate);
            act = dateFiltered;
        }

        if (keyword != null){
            var searchFiltered = act.FindAll(ex => ex.Title.Contains(keyword));
            act = searchFiltered;
        }
        
        return View(act);
    }

        
    [HttpPost]
    public IActionResult JoinAct(int Id)
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var acts = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        var act = acts.FirstOrDefault(a=> a.Ids == Id);
        Console.WriteLine(act.Title);
        Member mb = new Member{
            Users = new User{
                Name = HttpContext.Session.GetString("Name"),
                Pic = HttpContext.Session.GetString("Pic")
            },
            Status = "Pending"
        };

        act.Member.Add(mb);

        var updatedJson = JsonSerializer.Serialize(acts);
        System.IO.File.WriteAllText("./Database/Activity.json", updatedJson);
        return Ok("Success");
    }

    public IActionResult Act(int Id)
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var acts = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        var act = acts.FirstOrDefault(a=> a.Ids == Id);
        return View(act);
    }

    [HttpPost]
    public IActionResult AcceptMember(int user_id, int act_id)
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var acts = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        var act = acts.FirstOrDefault(a=> a.Ids == act_id);
        Console.WriteLine(act.Title);
        var user = act.Member.FirstOrDefault(a=> a.Users.Ids == user_id);
        user.Status = "Joined";


        var updatedJson = JsonSerializer.Serialize(acts);
        System.IO.File.WriteAllText("./Database/Activity.json", updatedJson);
        return Ok("Success");
    }


    [HttpPost]
    public IActionResult KickMember(int user_id, int act_id)
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var acts = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        var act = acts.FirstOrDefault(a=> a.Ids == act_id);
        Console.WriteLine(act.Title);
        var user = act.Member.FirstOrDefault(a=> a.Users.Ids == user_id);
        act.Member.Remove(user);

        var updatedJson = JsonSerializer.Serialize(acts);
        System.IO.File.WriteAllText("./Database/Activity.json", updatedJson);
        return Ok("Success");
    }

    [HttpPost]
    public IActionResult LeaveAct(int Id)
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var acts = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        var act = acts.FirstOrDefault(a=> a.Ids == Id);
        Console.WriteLine(act.Title);
        var user = act.Member.FirstOrDefault(a=> a.Users.Name == HttpContext.Session.GetString("Name"));
        act.Member.Remove(user);

        if (user.Status == "Host")
        {
            acts.Remove(act);
        }

        var updatedJson = JsonSerializer.Serialize(acts);
        System.IO.File.WriteAllText("./Database/Activity.json", updatedJson);
        return Ok("Success");
    }


    public IActionResult Setting()
    {
        if (TempData.ContainsKey("ErrorMessage"))
        {
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
        }
        return View();
    }

    public IActionResult Profile()
    {
        var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
        var act = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
        return View(act);
    }

    public IActionResult CreateActivity()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }




}

Touchgrass/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Touchgrass.Models;
using System.Text.Json;

namespace Touchgrass.Controllers;
public class LogoutController : Controller
{
    private readonly ILogger<LogoutController> _logger;
    
    public LogoutController(ILogger<LogoutController> logger)
    {
        _logger = logger;
    }
    
    [HttpPost]
    public IActionResult Logout()
    {
        HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();
        Response.Cookies.Delete(".AspNetCore.Session");
        return RedirectToAction("Login","Login");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Touchgrass/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Touchgrass.Models;
using System.Text.Json;


namespace Touchgrass.Controllers;
[Authorize]
public class SettingController : Controller
{
    private readonly ILogger<SettingController> _logger;

    private readonly IWebHostEnvironment _environment;
    
    public SettingController(ILogger<SettingController> logger, IWebHostEnvironment environment)
    {
        _logger = logger;
        _environment = environment;
    }

    [HttpPost]
    public IActionResult Picture(IFormFile filename)
    {
        if (filename != null && filename.Length > 0)
        {
            string uploadsFolder = Path.Combine(_environment.WebRootPath, "pic", "user");

            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }

            string uniqueFileName = Guid.NewGuid().ToString() + "_" + filename.FileName;

            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                filename.CopyTo(fileStream);
            }

            Uri baseUri = new Uri(_environment.WebRootPath + "/");
            Uri filePathUri = new Uri(filePath);
            Uri relativeUri = baseUri.MakeRelativeUri(filePathUri);
            string relativePath = "/" + relativeUri.ToString();

            Console.WriteLine(relativePath);

            var usrjson = System.IO.File.ReadAllText("./Database/User.json");
            var users = JsonSerializer.Deserialize<List<User>>(usrjson);
            var userToUpdate = users.FirstOrDefault(user => user.Name == HttpContext.Session.GetString("Name"));


            userToUpdate.Pic = relativePath; 


            var updatedJson = JsonSerializer.Serialize(users);

  

            var actjson = System.IO.File.ReadAllText("./Database/Activity.json");
            var acts = JsonSerializer.Deserialize<List<ActivityModel>>(actjson);
            foreach (var act in acts) {
                var user = act.Member.FirstOrDefault(a=> a.Users.Name == HttpContext.Session.GetString("Name"));
                if (user != null) {
                    user.Users.Pic = relativePath;
                }
            }
            var updatedJson2 = JsonSerializer.Serialize(acts);

            System.IO.File.WriteAllText("./Database/User.json", updatedJson);
            System.IO.File.WriteAllText("./Database/Activity.json", updatedJson2);

            HttpContext.Session.SetString("Pic", relativePath);

            return RedirectToAction("Setting","Home");
        }

        else {
            TempData["ErrorMessage"] = "Invalid";
            return RedirectToAction("Setting","Home");
        }
    }

public IActionResult Bio(string bio)
    {
        var usrjson = System.IO.File.ReadAllText("./Database/User.json");
        var users = JsonSerializer.Deserialize<List<User>>(usrjson);
        var userToUpdate = users.Find(user => user.Name == HttpContext.Session.GetString("Name"));  
        if (bio != null)
        {
            HttpContext.Session.SetString("Bio", bio);
        }

        else{
            HttpContext.Session.SetString("Bio", "");
        }

        userToUpdate.Bio = bio; 

        var updatedJson = JsonSerializer.Serialize(users);

  
        System.IO.File.WriteAllText("./Database/User.json", updatedJson);

        return RedirectToAction("Setting","Home");

    }

    [HttpPost]
    public IActionResult Password(string old_password, string new_password)
    {
        var usrjson = System.IO.File.ReadAllText("./Database/User.json");
        var users = JsonSerializer.Deserialize<List<User>>(usrjson);
        var userToUpdate = users.Find(user => user.Name == HttpContext.Session.GetString("Name"));  
        if (old_password != null && new_password != null && userToUpdate.Password == old_password )     
        {

            userToUpdate.Password = new_password; 


            var updatedJson = JsonSerializer.Serialize(users);

  
            System.IO.File.WriteAllText("./Database/User.json", updatedJson);

            return RedirectToAction("Setting","Home");
        }

        else {
            TempData["ErrorMessage"] = "Invalid";
            return RedirectToAction("Setting","Home");
        }
    }

   
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Touchgrass/Views/Home/Act.cshtml
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Touch Grass</title>

    <link rel="icon" type="image/png" href="~/img/touch-grass-logo.png">
    <link rel="stylesheet" href="~/css/ActStyle.css">
    
    @{
        ViewData["Title"] = "Activity ";

        @* string jsonModelTime = System.Text.Json.JsonSerializer.Serialize(Model.Time); *@
    }

    
</head>

<body>
    @* <div class="quick-btn">
        <p>↥</p>
    </div> *@
    <div class="my-container">
        <div class="main-container">
            <div class="slide-container">
                @foreach (var image in Model.Img) {
                    <div class="slide-content">
                        <img src=\@image class="background">
                        <img src=\@image class="show">
                    </div>
                }
                @* <div class="slide-content" style="display: block;">
                    <img src="~/img/mountain.jpg" class="background"></img>
                    <img src="~/img/mountain.jpg" class="show">
                </div>
                <div class="slide-content">
                    <img src="~/img/jungle.jpg" class="background"></img>
                    <img src="~/img/jungle.jpg" class="show">
                </div>
                <div class="slide-content">
                    <img src="~/img/panorama.jpg" class="background"></img>
                    <img src="~/img/panorama.jpg" class="show">
                </div>
                <div class="slide-content">
                    <img src="~/img/house.jpg" class="background"></img>
                    <img src="~/img/house.jpg" class="show">
                </div> *@

                <a class="prev" onclick="moveSlides(-1)">←</a>
                <a class="next" onclick="moveSlides(1)">→</a>

                @* <div class="dot-content">
                    <span class="dot active" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                    <span class="dot" onclick="currentSlide(4)"></span>
                </div> *@
            </div>

            <div class="tag-container">
                @foreach (var item in @Model.Tag) {
                    <a href="#" class="tag">
                        <div class="tag-type">@item</div>
                    </a>
                }
            </div>

            <div class="title-container">
                <div class="title-head">@Model.Title</div>
                <div class="title-content">
                    <div class="title-time">
                        <div class="time-icon">
                            <img src="/img/time.png">
                        </div>
                        <p class="time-data">
                            @Model.Date
                        </p>
                    </div>
                    <div class="title-place">
                        <div class="place-icon">
                            <img src="~/img/placeholder.png">
                        </div>
                        <p class="place-data">
                            @Model.Place
                        </p>
                    </div>
                </div>
            </div>

            <div class="info-container">
                <div class="info-head">
                    More Info
                </div>
                @{  
                    string description = Model.Description;
                    string[] infoArray = System.Text.RegularExpressions.Regex.Split(description, @"\n+");
                }
                <div class="info-content">
                    @foreach (var info in infoArray)
                    {
                        <div style="color: #6c707a;">@info</div>
                    }
                </div>
            </div>
        </div>
        <div class="side-container">
            <div class="responsive-flex">
                <div class="invite-container">
                    <div class="invite-head">Invitation will end in</div>
                    <div class="invite-timer" id="@Model.Date"></div>
                    @{var check = 0;}
                    @foreach (var mb in @Model.Member){
                        @if (mb.Users.Name == @Context.Session.GetString("Name")){
                            check = 1;
                            <button class="invite-btn" type="button" id="@Model.Ids">Joined</button>
                        }
                    }
                    @if (check == 0) {
                        <button class="invite-btn" type="button" onclick="event.stopPropagation();joinAct(this);" id="@Model.Ids">Join</button>
                    }
                </div>
                <div class="owner-container">
                    <div class="wrap-owner">
                        <img class="owner-img" src="@Model.Member[0].Users.Pic" alt="">
                        <div class="owner-content">
                            <div class="owner-head">Activity Owner</div>
                            <div class="owner-name">@Model.Member[0].Users.Name</div>
                            @* <button class="owner-btn">view account</button> *@
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="member-container">
                <p class="monitor-title">Activity Member</p>
                <div class="member-monitor">
                    <div class="limit-content">
                        <p class="member-limit">Party Goup: </p>
                        @{var memCount = 1;}
                        @foreach (var ppl in @Model.Member) {
                            if (ppl.Status == "Joined"){ memCount +=1;}
                        }
                        <div class="group-now">@memCount</div>
                        <div class="slash">/</div>
                        <div class="limit">@Model.MaxMember</div>
                    </div>
                    @* <div class="member-join">
                        <div class="join-main">
                            <div class="join">2</div>
                            <div class="require">6</div>
                        </div>
                        <img src="~/img/add-outside.png" class="add-outside">
                        <div class="outside">2</div>
                    </div> *@
                </div>
                <div class="member-display">
                    @foreach(var member in @Model.Member) {
                        <div class="member">
                            <div class="member-info">
                                <img src=@member.Users.Pic>
                                <div class="member-content">
                                    <p class="member-name">@member.Users.Name</p>
                                    <p class="member-status-join">@member.Status</p>
                                </div>
                            </div>
                            <div class="member-action">
                                @if (Context.Session.GetString("Name") == @Model.Host.Users.Name)  {
                                    if (member.Status != "Host") {
                                        if (member.Status == "Pending") {
                                            <button class="accept-btn" id="@member.Users.Ids" onclick="acceptMember(this)">Accept</button>
                                            <button class="kick-btn" id="@member.Users.Ids" onclick="kickMember(this)">Kick</button>
                                        } else if (member.Status == "Joined") {
                                            <button class="kick-btn" id="@member.Users.Ids" onclick="kickMember(this)">Kick</button>
                                        }
                                    } 
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>

<script src="~/js/activityScript.js"></script>
<script src="~/js/timer.js"></script>
<script src="~/js/statusColor.js"></script>

Touchgrass/Views/Home/CreateActivity.cshtml
@{
    List<string> restaurantTag = new List<string> {
"🍜 noodle",
"🥗 salad",
"🥓 muu kra ta",
"🍔 hamburgur",
"🥩 steak",
"🍝 pasta",
"🍕 pizza",
"🍣 sushi",
"🍛 curry",
"☕ café",
"🍨 ice cream",
"🍰 cake",
"🍻 alcohal",
"🍹 bar",
"🌃 rooftop",
"🎵 live music",
};

    List<string> sportTag = new List<string> {
"⚽ football",
"⚾ baseball",
"🏀 basketball",
"⛳ golf",
"🎾 tennis",
"🏐 volleyball",
"🏸 badminton",
"🥊 boxing",
"🏓 table tennis",
"🎱 snooker",
};

    List<string> activityTag = new List<string> {
"🚶 walking",
"💻 video game",
"🎲 boardgame",
"🎬 movie",
"🗺️ trip",
"🏔️ mountain",
"🏖️ beach",
"🎸 concert",
"🥁 music",
"📖 reading",
"🎨 art",
"🎊 party",
};
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/aecb1a01a7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="~/css/create_activity.css">
    <link href='https://fonts.googleapis.com/css?family=Itim' rel='stylesheet'>
    <script src="~/js/create_activity.js"></script>
</head>

<body>
    <main class="p main">
        <div style="position: relative;">
            <form method="post" asp-area="" asp-controller="CreateActivity" asp-action="CreateActivity"
                enctype="multipart/form-data" class="p">
                <h1 class="p header">Create Activity</h1>

                <label for="nameact" class="p">
                    <input class="p" type="text" name="Title" id="nameact" placeholder="Enter activity name" required>
                </label>

                <label for="images" class="p">
                    <div style="position: relative; width:100%;height:100%; background:none; min-height:400px">
                        <input type="file" name="Img" accept="image/*" id="images" onchange="getImg(event)" class="p" multiple>
                        <div class="p images-container"></div>
                    </div>
                </label>

                <label for="addresss" class="p">
                    <textarea id="addresss" title='address' onclick=openSearchAddress() rows="3"
                        placeholder="Enter the address" required name="Place" class="p"></textarea>
                </label>

                <label for="date" class="p act">
                    <input type="date" name="Date" id="datee" required class="p">
                </label>

                <div class='p nump'>
                    <label for="nop">
                        <div class="p max">max</div>
                        <input type="number" name="MaxMember" id="nop" min="2" max="999" value="2" required class="p">
                        <p class="p max">people</p>
                    </label>
                </div>

                <label for="descrip" class="p">
                    <textarea name="Description" id="descrip" rows="5" class="p"
                        placeholder="Enter your description"></textarea>
                </label>

                <div class="p tag" id="showTag">
                    <input type="checkbox" style="display: none;" name="Tag" class="p">
                    <i class="p fa-solid fa-plus addTag" onclick="getTag()"></i>
                </div>

                <button type="reset" class="p formbutton" onclick="getImg('reset')"><p class="btntext">Reset All</p></button>
                <button type="submit" class="p formbutton"><p class="btntext">Create!</p></button>
            </form>

            <div id="viewTag" class="p">
                <div class="p tagSet">
                    <button class="p done" onclick="closeTag()">done</button>
                    <div class="p inTag">
                        @foreach (var tag in restaurantTag)
                        {
                            <input type="checkbox" id="@($"{tag}1")" name="tags" class='p check' value='@tag'>
                            <label for="@($"{tag}1")" class='p checkstr'>@tag</label>
                        }
                        @foreach (var tag in sportTag)
                        {
                            <input type="checkbox" id="@($"{tag}1")" name="tags" class='p check' value='@tag'>
                            <label for="@($"{tag}1")" class='p checkstr'>@tag</label>
                        }
                        @foreach (var tag in activityTag)
                        {
                            <input type="checkbox" id="@($"{tag}1")" name="tags" class='p check' value='@tag'>
                            <label for="@($"{tag}1")" class='p checkstr'>@tag</label>
                        }
                        <i class="p fa-solid fa-plus checkstr" style="color:#fcfffc" onclick="getNewTag(this)"
                            aria-hidden="true"></i>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>

</html>

Touchgrass/Views/Home/Setting.cshtml
@{
    ViewData["Title"] = "Setting";
    var userPic = @Context.Session.GetString("Pic");
    var userBio = @Context.Session.GetString("Bio");
}
<div class="setting-container">
    <div class="setting-box">
        <p>Account</p>
        <a onclick="HSbyClass('.picture-box',event)">• User Picture</a>
        <div class="picture-box">
            <img class="current-picture" src="@userPic">
            <form method="post" asp-controller="Setting" asp-action="Picture" enctype="multipart/form-data">
                <input type="file" name="filename" accept="image/*">
                <button type="submit">Change Picture</button>
            </form>
        </div>
        <a onclick="HSbyClass('.bio-box',event)">• User Bio</a>
        <div class="bio-box">
            <form method="post" asp-controller="Setting" asp-action="Bio">
                <input type="text" name="bio" value="@userBio" placeholder="Write your Bios here!">
                <button type="submit">Change Infos</button>
            </form>
        </div>
        <a onclick="HSbyClass('.password-box',event)">• User Password</a>
        <div class="password-box">
            <form method="post" asp-controller="Setting" asp-action="Password" class="change-password">
                <input class="old-password" type="password" placeholder="old-password" name="old_password">
                <input class="new-password" type="password" placeholder="new-password" name="new_password">
                <button type="submit">Save Changes</button>
            </form>
        </div>
        <a onclick="HSbyClass('.logout-box',event)">• Log Out</a>
        <div class="logout-box">
            <form method="post" asp-controller="Logout" asp-action="Logout" class="logout">
                <button type="submit">Log Out</button>
            </form>
        </div>
    </div>
</div>
@if(ViewBag.ErrorMessage != null)
{
    <script>
        window.onload = function() {
            alert("@ViewBag.ErrorMessage");
        };
    </script>
}